# Generated by Django 2.0.13 on 2020-12-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('value', models.CharField(max_length=100)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=100)),
                ('info_url', models.TextField()),
            ],
        ),
    ]
