# Generated by Django 2.0.13 on 2021-01-05 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=100)),
                ('info_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='R_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, editable=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('W', '여자'), ('M', '남자')], max_length=2)),
                ('personality', models.CharField(choices=[('외향', '외향형'), ('내향', '내향형')], max_length=2)),
                ('activity', models.BooleanField()),
                ('job', models.CharField(max_length=100)),
                ('interested', models.TextField()),
                ('school', models.BooleanField()),
                ('work', models.BooleanField()),
                ('abode', models.CharField(choices=[('I.C', '국내 수도권'), ('I.P', '국내 지방'), ('F', '해외')], max_length=5)),
                ('siblings', models.IntegerField()),
                ('family', models.IntegerField()),
                ('livealone', models.BooleanField()),
                ('major', models.CharField(choices=[('이', '이과'), ('문', '문과')], max_length=10)),
                ('homeeconomy', models.CharField(blank=True, choices=[('L', '부족함'), ('A', '넉넉함'), ('H', '부유함')], max_length=10)),
                ('havedate', models.BooleanField()),
                ('physicaltrouble', models.NullBooleanField()),
                ('mentaltrouble', models.NullBooleanField()),
                ('prefergenre', models.TextField()),
                ('preferchannel', models.CharField(choices=[('지상파', '지상파'), ('케이블', '케이블')], max_length=10)),
                ('watchingtime', models.CharField(choices=[('D', '6-18시'), ('N', '18-6시')], max_length=50)),
                ('used', models.CharField(choices=[('L', 'TV 또는 빔 프로젝터'), ('M', '컴퓨터(데스크탑)'), ('S', '휴대용 기기(노트북, 휴대폰 등)')], max_length=10)),
                ('way', models.CharField(choices=[('O', '본방송'), ('R', '재방송'), ('V', '다시보기 다운로드(유료 또는 무료)'), ('P', '다시보기, 연재작(온라인 콘텐츠 플랫폼 ex.NETFLIX, 왓챠)')], max_length=10)),
                ('first', models.TextField()),
                ('second', models.TextField()),
                ('third', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('W', '여자'), ('M', '남자')], max_length=2)),
                ('personality', models.CharField(choices=[('외향', '외향형'), ('내향', '내향형')], max_length=2)),
                ('activity', models.BooleanField()),
                ('job', models.CharField(max_length=100)),
                ('interested', models.TextField()),
                ('school', models.BooleanField()),
                ('work', models.BooleanField()),
                ('abode', models.CharField(choices=[('I.C', '국내 수도권'), ('I.P', '국내 지방'), ('F', '해외')], max_length=5)),
                ('siblings', models.IntegerField()),
                ('family', models.IntegerField()),
                ('livealone', models.BooleanField()),
                ('major', models.CharField(choices=[('이', '이과'), ('문', '문과')], max_length=10)),
                ('homeeconomy', models.CharField(blank=True, choices=[('L', '부족함'), ('A', '넉넉함'), ('H', '부유함')], max_length=10)),
                ('havedate', models.BooleanField()),
                ('physicaltrouble', models.NullBooleanField()),
                ('mentaltrouble', models.NullBooleanField()),
                ('prefergenre', models.TextField()),
                ('preferchannel', models.CharField(choices=[('지상파', '지상파'), ('케이블', '케이블')], max_length=10)),
                ('watchingtime', models.CharField(choices=[('D', '6-18시'), ('N', '18-6시')], max_length=50)),
                ('used', models.CharField(choices=[('L', 'TV 또는 빔 프로젝터'), ('M', '컴퓨터(데스크탑)'), ('S', '휴대용 기기(노트북, 휴대폰 등)')], max_length=10)),
                ('way', models.CharField(choices=[('O', '본방송'), ('R', '재방송'), ('V', '다시보기 다운로드(유료 또는 무료)'), ('P', '다시보기, 연재작(온라인 콘텐츠 플랫폼 ex.NETFLIX, 왓챠)')], max_length=10)),
                ('first', models.TextField()),
                ('second', models.TextField()),
                ('third', models.TextField()),
            ],
        ),
    ]
